### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by junosuarez** [7sharp9/edge-fs#2]
In your [blog post](http://7sharpnine.com/posts/i-node-something/) you mentioned plans to publish `edge-fs` to npm once things settled down. I would recommend publishing what you have so far (maybe with a disclaimer). This makes it much easier for people to discover, use, and contribute to your module in the node ecosystem.

**Comment by 7sharp9** [comment]
I did plan to, as usual I got sidetracked on other projects, names ScriptCS.  As far as I know its pretty stable, I need more examples and some docs to go with it.  Let me se if I can get it published tonight.
